### ISSUE TITLE
Data fields not found

### ISSUE THREAD

**Issue by wattsjus** [warren-bank/node-hls-downloader-tubitv#3]
WHen trying to download a single movie I am getting the following error:

Error: Assertion Error: missing data fields in video object metadata for movie video stream in server response at URL: '***'
    at process_video_data (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/lib/process_cli.js:161:15)
    at process_html (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/lib/process_cli.js:104:15)
    at process_url (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/lib/process_cli.js:66:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async process_argv (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/lib/process_cli.js:338:7)

The command I used was:
 tubidl -q -mc 5 -u '***'

**Comment by warren-bank** [comment]
since you didn't say which movie you were unable to download,<br>I just chose one off the top of my head to test:

```bash
tubidl -mc 5 --log-level 3 -u "https://tubitv.com/movies/490355/highlander-the-movie"
```

..works fine

my guess is that your particular movie is probably DRM protected,<br>but I can't say for certain without knowing which one it is
* the API response for videos that are DRM protected is slightly different
* [this userscript](https://github.com/warren-bank/crx-Tubi-TV)
  - will clearly indicate whether a video is DRM protected or not
  - makes it easy to play any TubiTV video (DRM protected or not) in ExoPlayer on Android
* but you won't be able to download it for offline viewing.. or conversion to mp4

**Comment by Braklet** [comment]
Hi there, just got this error with a specific TV series:

```
tubidl -mf 1 -mc 2 -u https://tubitv.com/series/300002691/sanford-and-son
Error: Assertion Error: missing data fields in video object metadata for episode video stream in server response at URL: 'https://tubitv.com/tv-shows/200051812'
```
I confirmed that the latest downloader (v10.8.1) as of this date works correctly with other TV series.
Not sure how to run your crx-Tubi-TV script to check DRM status, though.

**Comment by warren-bank** [comment]
@Braklet duplicate to #4 &rarr; DRM protected

RE the [_crx-Tubi-TV_](https://github.com/warren-bank/crx-Tubi-TV/raw/webmonkey-userscript/es5/webmonkey-userscript/Tubi-TV.user.js) userscript: [TamperMonkey](https://www.tampermonkey.net/), [GreaseMonkey](https://en.wikipedia.org/wiki/Greasemonkey), [Android WebMonkey](https://github.com/warren-bank/Android-WebMonkey), etc..

**Comment by Braklet** [comment]
> @Braklet duplicate to #4 → DRM protected
> 
> RE the [_crx-Tubi-TV_](https://github.com/warren-bank/crx-Tubi-TV/raw/webmonkey-userscript/es5/webmonkey-userscript/Tubi-TV.user.js) userscript: [TamperMonkey](https://www.tampermonkey.net/), [GreaseMonkey](https://en.wikipedia.org/wiki/Greasemonkey), [Android WebMonkey](https://github.com/warren-bank/Android-WebMonkey), etc..

Very helpful, thanks!  Confirmed DRM status of Sanford And Son, and non-DRM status of Freak Brothers.  Interesting work.

**Comment by 3052** [comment]
> Hi there, just got this error with a specific TV series:
> 
> ```
> tubidl -mf 1 -mc 2 -u https://tubitv.com/series/300002691/sanford-and-son
> Error: Assertion Error: missing data fields in video object metadata for episode video stream in server response at URL: 'https://tubitv.com/tv-shows/200051812'
> ```
> 
> I confirmed that the latest downloader (v10.8.1) as of this date works correctly with other TV series. Not sure how to run your crx-Tubi-TV script to check DRM status, though.

I have a working tool, but  you have to provide individual episode not the entire show:

~~~
10:05:46 INFO GET URL="https://akamai2.tubi.video/5aea88fa-6c02-4d87-9e61-642755374347/owo56g0lri.mpd?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZG5fcHJlZml4IjoiaHR0cHM6Ly9ha2FtYWkyLnR1YmkudmlkZW8iLCJleHAiOjE3MjkwODM2MDAsIm1lZGlhX3NpZyI6MTEzMzM3Mjd9.1a4Thw05JXOjrgAhrIT5uzxGkwEb7z21lpRXhOhaeP4"
10:05:46 INFO GET URL=https://akamai2.tubi.video/5aea88fa-6c02-4d87-9e61-642755374347/xozzgqrn.mp4
10:05:46 INFO POST URL="https://license.adrise.tv/challenge?platform=android&type=widevine&external_id=629254FE3F86F39D88A489908DCA6B34&drm_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbmFsb2dfb3V0IjoiY2dtc19yZXF1aXJlZCIsImV4cCI6MTcyODk5NzIwMCwiaGRjcCI6InYxIiwicHJfc2VjdXJpdHlfbGV2ZWwiOjIwMDAsInd2X3NlY3VyaXR5X2xldmVsIjoxfQ.uxdStpw2Z0E6R3I7kjKa-zcNYHs3rR7bXgO1UFyFG3w"
10:05:47 INFO CDM PSSH=EhBsOj6a38pMB4euCINieo6kSOPclZsG key="TMw+mgWh9VmBOloPtuB/PA=="
10:05:47 INFO GET URL=https://akamai2.tubi.video/5aea88fa-6c02-4d87-9e61-642755374347/xozzgqrn.mp4
10:05:48 INFO 2.71 % size="10.19 megabyte" rate="10.19 megabyte/s"
~~~
