### ISSUE TITLE
--help doesn't seem to work

### ISSUE THREAD

**Issue by ileGITimo** [warren-bank/node-hls-downloader-tubitv#7]
% tubidl --help
/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/bin/tubitv-downloader/help.js:38
      1 = "${movie-or-episode-title}.mp4"
             ^

ReferenceError: movie is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/bin/tubitv-downloader/help.js:38:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/bin/tubitv-downloader/process_argv.js:45:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

**Comment by warren-bank** [comment]
thanks for catching that.. it was a dumb bug.. introduced in [v1.5.0](https://github.com/warren-bank/node-hls-downloader-tubitv/releases/tag/v1.5.0).. fixed in [v1.5.1](https://github.com/warren-bank/node-hls-downloader-tubitv/releases/tag/v1.5.1) by [this commit](https://github.com/warren-bank/node-hls-downloader-tubitv/commit/ed301e31686f39c2382e8a048f162151610d889c).

**Comment by ileGITimo** [comment]
Thanks for fixing it.  I was checking your method as a way to get subtitles, if I ever need them. I usually just get the m3u8 url with Firefox dev mode. then feed it to ffmpeg.
